package kantor;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Nurul AD
 */
public class inputdata_admin extends javax.swing.JFrame {
    Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;


    /**
     * Creates new form inputdata_admin
     */
    public inputdata_admin() {
        initComponents();
          load_table();
    }
    private void load_table(){
// membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Data");
        model.addColumn("Divisi");
        model.addColumn("Nota Dinas");
        model.addColumn("Tanggal");
        model.addColumn("Aplikasi");
        model.addColumn("Pemanfaatan");
        model.addColumn("Jenis Kegiatan");
        model.addColumn("Kendala");
        model.addColumn("Penanganan");
        model.addColumn("Keterangan");
        model.addColumn("Status");
        
        //menampilkan data database kedalam tabel
        try {
            
            String sql = "select * from data";
            java.sql.Connection conn=(Connection)koneksi.koneksi();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10),res.getString(11)});
            }
            tb.setModel(model);
        } catch (Exception e){ }
    }
    private void kosong(){
        infopemanfaatan.setText(null);
        infokegiatan.setText(null);
        infokendala.setText(null);
        infopenanganan.setText(null); 
        infoketerangan.setText(null);  
        infoaplikasi.setText(null);
        infokode.setText(null);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        infoid = new javax.swing.JLabel();
        infolevel = new javax.swing.JLabel();
        infodivisi = new javax.swing.JTextField();
        notadinas = new javax.swing.JTextField();
        infotanggal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        infoaplikasi = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        infopemanfaatan = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        infokegiatan = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        infokendala = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        infopenanganan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        infoketerangan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        infostatus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        infokode = new javax.swing.JTextField();
        infocari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 322, 1006, 183));

        jLabel1.setText("Login dengan ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setText("Level Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setText("Divisi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setText("Nota Dinas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setText("Tanggal");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        infoid.setText("id");
        getContentPane().add(infoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 70, 20));

        infolevel.setText("Level");
        getContentPane().add(infolevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 70, 20));
        getContentPane().add(infodivisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, 30));

        notadinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notadinasActionPerformed(evt);
            }
        });
        getContentPane().add(notadinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 130, 30));
        getContentPane().add(infotanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, 30));

        jLabel6.setText("Aplikasi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 40, 20));

        jLabel7.setText("Pemanfaatan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, 20));

        jLabel8.setText("Jenis Kegiatan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, 20));
        getContentPane().add(infoaplikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 160, 30));

        infopemanfaatan.setColumns(20);
        infopemanfaatan.setRows(5);
        jScrollPane3.setViewportView(infopemanfaatan);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        infokegiatan.setColumns(20);
        infokegiatan.setRows(5);
        jScrollPane4.setViewportView(infokegiatan);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel9.setText("Kendala");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        infokendala.setColumns(20);
        infokendala.setRows(5);
        jScrollPane5.setViewportView(infokendala);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        jLabel10.setText("Penanganan");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));
        getContentPane().add(infopenanganan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 160, 30));

        jLabel11.setText("Keterangan");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));
        getContentPane().add(infoketerangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 160, 30));

        jLabel12.setText("Status");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));
        getContentPane().add(infostatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 160, 30));

        jButton1.setText("Tambah");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, -1, -1));

        bedit.setText("update");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        getContentPane().add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, -1, -1));

        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, -1, -1));

        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, -1, -1));

        jLabel13.setText("Kode Data");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        getContentPane().add(infokode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 130, 30));

        infocari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infocariActionPerformed(evt);
            }
        });
        getContentPane().add(infocari, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 190, 30));

        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        getContentPane().add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notadinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notadinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notadinasActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
     try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/beacukai","root","");
            cn.createStatement().executeUpdate("update data set divisi='"+infodivisi.getText()+"',notadinas= '"+notadinas.getText()+"',tanggal= '"+infotanggal.getText()+"',aplikasi= '"+infoaplikasi.getText()+"',pemanfaatan= '"+infopemanfaatan.getText()+"',jeniskegiatan= '"+infokegiatan.getText()+"',kendala= '"+infokendala.getText()+"',penanganan= '"+infopenanganan.getText()+"',keterangan= '"+infoketerangan.getText()+"',status= '"+infostatus.getText()+"' WHERE kd_data = '"+infokode.getText()+"'");
            load_table();
         
        } catch (SQLException ex) {
            Logger.getLogger(inputdata_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_beditActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/beacukai","root","");
            cn.createStatement().executeUpdate("delete from data where kd_data='"+infokode.getText()+"'");
            load_table();
        } catch (SQLException ex) {
            Logger.getLogger(inputdata_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    
    }//GEN-LAST:event_bhapusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        login back = new login();
       back.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
                                            
        // menampilkan data kedalam form pengisian:
        int baris = tb.rowAtPoint(evt.getPoint());
        
        String divisi =tb.getValueAt(baris, 1).toString();
        infodivisi.setText(divisi);
        
        String nota =tb.getValueAt(baris, 2).toString();
        notadinas.setText(nota);
        
        String tgl =tb.getValueAt(baris, 3).toString();
        infotanggal.setText(tgl);

        String aplikasi =tb.getValueAt(baris, 4).toString();
        infoaplikasi.setText(aplikasi);
        
        String pemanfaatan =tb.getValueAt(baris, 5).toString();
        infopemanfaatan.setText(pemanfaatan);
        
        String jenis =tb.getValueAt(baris, 6).toString();
        infokegiatan.setText(jenis);
        
        String kendala =tb.getValueAt(baris, 7).toString();
        infokendala.setText(kendala);
       
        String penanganan =tb.getValueAt(baris, 8).toString();
        infopenanganan.setText(penanganan);
        
       String ket =tb.getValueAt(baris, 9).toString();
       infoketerangan.setText(ket);
               
       String sts =tb.getValueAt(baris, 10).toString();
       infostatus.setText(sts);
        
       String kd =tb.getValueAt(baris, 0).toString();
       infokode.setText(kd);
        
        
        
    }//GEN-LAST:event_tbMouseClicked

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
    
    }//GEN-LAST:event_bcariActionPerformed

    private void infocariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infocariActionPerformed
 
    }//GEN-LAST:event_infocariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputdata_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputdata_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputdata_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputdata_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputdata_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JTextField infoaplikasi;
    private javax.swing.JTextField infocari;
    private javax.swing.JTextField infodivisi;
    private javax.swing.JLabel infoid;
    private javax.swing.JTextArea infokegiatan;
    private javax.swing.JTextArea infokendala;
    private javax.swing.JTextField infoketerangan;
    private javax.swing.JTextField infokode;
    private javax.swing.JLabel infolevel;
    private javax.swing.JTextArea infopemanfaatan;
    private javax.swing.JTextField infopenanganan;
    private javax.swing.JTextField infostatus;
    private javax.swing.JTextField infotanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField notadinas;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables

 
    
}
