
package kantor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nurul AD
 */
public class inputdata_user extends javax.swing.JFrame {
   
    Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;

String id_log = sessionn.get_Id_Log();
String level = sessionn.get_Level();

    /**
     * Creates new form inputdata_user
     */
    public inputdata_user() {
        initComponents();
        autokode();
        tanggal_jam_sekarang();
        load_table();
        kosong();
        conn = koneksi.koneksi();
        String query = "SELECT * FROM profile WHERE id_log=?";
        try{
            pst = conn.prepareStatement(query);
            pst.setString(1, id_log);
            rs = pst.executeQuery();
            while (rs.next()){
                idlog.setText(id_log);
                infolevel.setText(level);
                infodivisi.setText(rs.getString("divisi"));
        
            
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        
        
    }
    
    
private void autokode(){
try{ koneksi.koneksi(); //--> memanggil koneksi
        //--> melakukan eksekusi query untuk mengambil data dari tabel
    String sql= "SELECT MAX(right(kd_data,5)) AS no FROM data";
    java.sql.Connection conn=(Connection)koneksi.koneksi();
    java.sql.Statement stm=conn.createStatement();
    ResultSet rs = stm.executeQuery(sql);
        while(rs.next())
            {
                if(rs.first() == false)
                {
        infokode.setText("ID-000001");
       

 
}
                else
        {
                   rs.last();
                   int auto_id = rs.getInt(1) + 1;
                   String no = String.valueOf(auto_id);
                   int noLong = no.length();
                   //MENGATUR jumlah 0
                    for(int a=0;a<6-noLong;a++)
                    {
                        no = "0" + no;
                    }
                   infokode.setText("ID-" + no);
               
                 }       
            }
       rs.close();
       stm.close();
}   
catch (Exception e){
            JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(),
                            "Kesalahan", JOptionPane.WARNING_MESSAGE);

        }
}
    
    
    
private void kosong(){
        infopemanfaatan.setText(null);
        infokegiatan.setText(null);
        infokendala.setText(null);
        infopenanganan.setText(null); 
        infoketerangan.setText(null);  
        jComboBox.setSelectedItem(this);
    }
private void load_table(){
// membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Data");
        model.addColumn("Divisi");
        model.addColumn("Nota Dinas");
        model.addColumn("Tanggal");
        model.addColumn("Aplikasi");
        model.addColumn("Pemanfaatan");
        model.addColumn("Jenis Kegiatan");
        model.addColumn("Kendala");
        model.addColumn("Penanganan");
        model.addColumn("Keterangan");
        model.addColumn("Status");
        
        //menampilkan data database kedalam tabel
        try {
            
            String sql = "select * from data";
            java.sql.Connection conn=(Connection)koneksi.koneksi();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10),res.getString(11)});
            }
            tb.setModel(model);
        } catch (Exception e){ }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        infodivisi = new javax.swing.JTextField();
        infolevel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        notadinas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        infotanggal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        infopemanfaatan = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infokegiatan = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        infopenanganan = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        infokendala = new javax.swing.JTextArea();
        infoketerangan = new javax.swing.JTextField();
        btsimpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        infostatus = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        infokode = new javax.swing.JTextField();
        idlog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("Login dengan ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setText("Level Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setText("Divisi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        jPanel1.add(infodivisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, 30));

        infolevel.setText("Level");
        jPanel1.add(infolevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, 10));

        jLabel4.setText("Nota Dinas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        jPanel1.add(notadinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 160, 30));

        jLabel5.setText("Tanggal");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        jPanel1.add(infotanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 160, 30));

        jLabel6.setText("Aplikasi");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLabel7.setText("Pemanfaatan");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CEISA Pembendaharaan", "Biling System", "SIAPTANDING", "Regina", "CEISA TPB", "Sistem Aplikasi Cukai (ExSIS)", " " }));
        jPanel1.add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 160, -1));

        infopemanfaatan.setColumns(20);
        infopemanfaatan.setRows(5);
        jScrollPane1.setViewportView(infopemanfaatan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jLabel8.setText("Jenis Kegiatan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        infokegiatan.setColumns(20);
        infokegiatan.setRows(5);
        jScrollPane2.setViewportView(infokegiatan);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jLabel9.setText("Kendala");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        jLabel10.setText("Penanganan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        jLabel11.setText("Keterangan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));
        jPanel1.add(infopenanganan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 130, 30));

        infokendala.setColumns(20);
        infokendala.setRows(5);
        jScrollPane3.setViewportView(infokendala);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, 110));
        jPanel1.add(infoketerangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 130, 30));

        btsimpan.setText("Simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, -1, -1));

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, -1, -1));

        tb.setBackground(new java.awt.Color(153, 153, 153));
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(tb);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 332, 1030, 230));

        jLabel12.setText("Status");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 50, -1));

        infostatus.setText("Proses");
        jPanel1.add(infostatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 130, 30));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        waktu.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        jLabel14.setText("Kode Data");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 10));
        jPanel1.add(infokode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, 30));

        idlog.setText("id");
        jPanel1.add(idlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
         try {
            String sql = "INSERT INTO data VALUES ('"+infokode.getText()+"','"+infodivisi.getText()+"','"+notadinas.getText()+"','"+infotanggal.getText()+"','"+jComboBox.getSelectedItem()+"',"
                    + "'"+infopemanfaatan.getText()+"','"+infokegiatan.getText()+"','"+infokendala.getText()+"','"+infopenanganan.getText()+"','"+infoketerangan.getText()+"','"+infostatus.getText()+"')";
            java.sql.Connection conn=(Connection)koneksi.koneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
         kosong();
         autokode();
         load_table();
    }//GEN-LAST:event_btsimpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       login back = new login();
       back.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbAncestorAdded
        {
        }
    }//GEN-LAST:event_tbAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputdata_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputdata_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputdata_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputdata_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputdata_user().setVisible(true);
            }
        });
    }

      public void tanggal_jam_sekarang(){
    Thread p=new Thread(){
    public void run(){
    for(;;){
    
        
        Calendar cal = new GregorianCalendar();
        int hari = cal.get(Calendar.DAY_OF_MONTH);
        int bulan = cal.get(Calendar.MONTH);
        int tahun = cal.get(Calendar.YEAR);
        infotanggal.setText(tahun+"-"+(bulan+1)+"-"+hari);
        
        int jam = cal.get(Calendar.HOUR);
        int menit = cal.get(Calendar.MINUTE);
        int detik = cal.get(Calendar.SECOND);
        int AM_PM = cal.get(Calendar.AM_PM);
        
        String day_night = "";
        if (AM_PM == 1)
        {
            day_night = "PM";
        }
        else
        {
            day_night = "AM";
        }
        String waktu1 = jam+":"+menit+":"+detik+""+day_night;
        waktu.setText(waktu1);
        
        try{
        sleep(1000);
        }catch(InterruptedException ex){
            Logger.getLogger(inputdata_user.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }
    };
    p.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btsimpan;
    private javax.swing.JLabel idlog;
    private javax.swing.JTextField infodivisi;
    private javax.swing.JTextArea infokegiatan;
    private javax.swing.JTextArea infokendala;
    private javax.swing.JTextField infoketerangan;
    private javax.swing.JTextField infokode;
    private javax.swing.JLabel infolevel;
    private javax.swing.JTextArea infopemanfaatan;
    private javax.swing.JTextField infopenanganan;
    private javax.swing.JTextField infostatus;
    private javax.swing.JTextField infotanggal;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField notadinas;
    private javax.swing.JTable tb;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
